name: Linux

on:
  push:
  pull_request:
    branches: [ "latest" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  default_features:
    name: Default Features
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v3
      - name: Checkout submodules
        run: git submodule update --init
      - name: Update Rust
        run: |
          rustup update ${{ matrix.toolchain }}
          rustup default ${{ matrix.toolchain }}
      - name: Build
        run: cargo build --verbose
      - name: Run Tests
        run: cargo test --verbose
  linux_features:
    name: All Linux Features
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - name: Install Prereqs
        run: |
          sudo apt-get update
          sudo apt-get install libsystemd-dev
      - uses: actions/checkout@v3
      - name: Checkout submodules
        run: git submodule update --init
      - name: Update Rust
        run: |
          rustup update ${{ matrix.toolchain }}
          rustup default ${{ matrix.toolchain }}
      - name: Build
        run: cargo build --verbose --features journald,network,socket
      - name: Run Tests
        run: cargo test --verbose --features journald,network,socket
