name: Mac

on:
  push:
  pull_request:
    branches: [ "latest" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  default_features:
    name: Default Features
    runs-on: macos-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v3
      - name: Checkout submodules
        run: git submodule update --init
      - run: rustup update ${{ matrix.toolchain }}
      - run: rustup default ${{ matrix.toolchain }}
      - run: cargo build --verbose
      - run: cargo test --verbose
  mac_features:
    name: All Mac Features
    runs-on: macos-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v3
      - name: Checkout submodules
        run: git submodule update --init
      - run: rustup update ${{ matrix.toolchain }}
      - run: rustup default ${{ matrix.toolchain }}
      - run: cargo build --verbose --features network,socket
      - run: cargo test --verbose
